### ISSUE TITLE
Symbol conflict 

### ISSUE THREAD

**Issue by cdaringe** [wranggle/rpc#11]
# Problem

`Import declaration conflicts with local declaration of 'Event'.ts(2440)`

![image](https://user-images.githubusercontent.com/1003261/97095803-e9a71700-1618-11eb-86e0-830ec320bcb4.png)

TS cannot compile due to symbol conflicts.

**Comment by ferbs** [comment]
I'm using completely different code now for websocket rpc transports in my own projects but haven't updated this repo.
(Low/zero use and I find its typescript/jest/lerna/yarn setup generally unpleasant.)

Let me know if you ended up using WranggleRpc though and I can either pass along my changes unofficially or make the updates. 

Thanks for taking the time to point out the problem, this and the other issues. The current `rpc-websocket-transport` is now deprecated and marked-for-replacement though, so will close this issue.
