### ISSUE TITLE
 UnhandledPromiseRejectionWarning:Unable to creat transport instance from passed in options

### ISSUE THREAD

**Issue by vilianfung** [wranggle/rpc#3]
Hi:
   I am writing a electron app and meet a problem,Give me some help pls:
I would like to use another render process to do heavy work, Rpc like this:
Render(normal)<-->Main<-->Render(Heavy work)
Render normal refs to mainWindow, and  heavy task Render refs to  backendWindow
In Normal Render:
const foreRpc = new WranggleRpc({
    debug:true,
    electron: {
        ipcChannel:'fore',
        ipcReceiver: ipcRenderer,
        ipcSender: ipcRenderer,
    }
});
In Main:
  rpc =new WranggleRpc({
    debug:true,
    transport:new Relay({
      left: new ElectronTransport({
        ipcChannelReceiving:'fore',
        ipcReceiver: ipcMain,
        ipcSender: backendWindow.webContents
      }),
      right: new ElectronTransport({
        ipcChannelReceiving:'backend',
        ipcReceiver: ipcMain,
        ipcSender: mainWindow.webContents
      }),
    })
In Heavy Work Render:
const backendRpc = new WranggleRpc({
    electron: {
        ipcChannel:'backend',
        ipcReceiver: ipcRenderer,
        ipcSender: ipcRenderer,
    }
});

1.Am I right,refs to above usage?
2.What's the problem about this error when start up:

(node:31647) UnhandledPromiseRejectionWarning: Error: Unable to creat transport instance from passed in options
    at Object.buildTransport (/Users/vilivanfung/XJMessenger/node_modules/@wranggle/rpc-core/dist/cjs/internal/transport-construction.js:34:15)
    at Router.useTransport (/Users/vilivanfung/XJMessenger/node_modules/@wranggle/rpc-core/dist/cjs/internal/router.js:18:67)
    at Router.routerOpts (/Users/vilivanfung/XJMessenger/node_modules/@wranggle/rpc-core/dist/cjs/internal/router.js:59:32)
    at WranggleRpc.opts (/Users/vilivanfung/XJMessenger/node_modules/@wranggle/rpc-core/dist/cjs/core.js:66:21) 

Thank you In Advanced!

**Comment by vilianfung** [comment]
finally I solved the problems by replace ipcChannelReceiving with ipcChannel ,but UnhandledPromiseRejectionWarning always exists when electron app startup!

**Comment by ferbs** [comment]
Make sure ipcChannel is the same value for both sender and receiver. You don't really need to set it, the default is usually fine. And be careful about confusing it with the main WranggleRpc "channel" option, they are different.

Regarding UnhandledPromiseRejectionWarning, are you using Electron v5? Looks like it uses Node v12. I haven't tried or tested it on Node 12 yet and am not surprised that it'll need some more catch or try/catch statements. I'm not focusing on WranggleRpc now but should have time to look at PRs if you want to submit any.

**Comment by vilianfung** [comment]
Than you for your good job,I save me a lot of time.
ps: I am using eletron v5

**Comment by ferbs** [comment]
Thanks for saying so! I usually don't release my work but thought people writing browser extensions and Electron apps would like this one. The response was mostly a turnoff though, so good to hear you like it. (eg, I mentioned it to Discord, offered my help, and they deleted my post.)
