### ISSUE TITLE
@wrangle/rpc & Wildcard

### ISSUE THREAD

**Issue by brillout** [wranggle/rpc#5]
Hi!

I like what you've done. Didn't think about the use case of inter browser communication. Neat...

I've built [Wildcard API](https://github.com/reframejs/wildcard-api), what do you think? It's RPC but more for browser <-> Node.js server.

**Comment by ferbs** [comment]
I like the interface for registering endpoints. Wildcard uses websockets? (I didn't look at the src.) 
I mainly needed @wranggle/rpc to handle various transport types, especially when relaying was involved. The tipping point was when my code in an Electron app renderer process had to interact with a Chrome extension.
